name: docking
channels:
  - conda-forge
  - bioconda
  - hcc
dependencies:
  - numpy
  - pdb_manip_py==1.3.10
  - os_command_py==1.1.0
  - python>=3.5
  - mgltools
  - smina
  - autodock-vina
  - qvina
  - autodock
  - pytest
  - pip