name: docking
channels:
  - conda-forge
  - bioconda
  - hcc
dependencies:
  - numpy
  - pdb_manip_py
  - os_command_py
  - python>=3.5
  - mgltools=1.5.6
  - smina
  - autodock-vina
  - qvina
  - autodock