language: generic

# Doesn't matter, tox will test py35, py36, py37 and py38
python:
  - "3.8"

env:
  - PYTHON_VERSION="3.8"

matrix:
    include:
        - os: linux
        - os: osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; 
      then 
        sudo apt-get update; 
        MINICONDA_OS=Linux; 
      else 
        MINICONDA_OS=MacOSX; 
    fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda config --add channels acellera
  - conda create -q --name docking python=$PYTHON_VERSION smina autodock-vina qvina mgltools=1.5.6
  - conda activate docking
  # Need to update pip, setuptools and wheel only for python3.5
  - pip install -U pip setuptools wheel 
  # Install tox-travis to use tox in travis
  # - pip install tox-travis tox-conda
  - pip install tox-conda
  - pip install -r requirements.txt

script:
  - tox

after_success:
  - codecov