# Config file for automatic testing at travis-ci.com

# Inspired by :
# https://github.com/astropy/ci-helpers/blob/master/.travis.yml
# And:
# https://github.com/Becksteinlab/GromacsWrapper/blob/master/.travis.yml

language: generic

os:
  - linux

git:
  depth: false

branches:
  only:
    - master

env:
  global:
    - PYTHON_VERSION=3.6
    - CONDA_DEPENDENCIES="pandoc ipython mgltools smina vina qvina"
    - CONDA_CHANNELS="conda-forge bioconda acellera"



# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  # Install astropy to build python and gromacs with conda
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  # Install gromacs_py
  - pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: samuel.murail
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: samuelmurail/docking_py
    python: 3.8
